fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ok_mix_ok:
    resource: "@OKMixOkBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
